frontend/modules/painter/models/BankingInformation.php
<?php

namespace app\modules\painter\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;
use yii\db\Expression;

/**
 * This is the model class for table "banking_information".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $bank_name
 * @property string $account_name
 * @property integer $account_number
 * @property string $IP
 * @property string $created_datetime
 * @property string $updated_datetime
 * @property integer $created_by
 * @property integer $updated_by
 */
class BankingInformation extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'banking_information';
    }
    
    public function behaviors() {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_datetime',
                'updatedAtAttribute' => 'updated_datetime',
                'value' => new Expression('NOW()'),
            ],
            BlameableBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['bank_name', 'account_name', 'account_number'], 'required'],
            [['user_id', 'bank_name', 'account_number', 'created_by', 'updated_by'], 'integer'],
            [['created_datetime', 'updated_datetime'], 'safe'],
            [['account_name'], 'string', 'max' => 255],
            [['account_ic_no'], 'string', 'max' => 12],
            [['account_no_verification'], 'string', 'max' => 1],
            [['IP'], 'string', 'max' => 50],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'bank_name' => 'Bank Name',
            'account_name' => 'Name of Account Holder',
            'account_number' => 'Account Number',
            'account_ic_no' => 'Account Holder NRIC',
            'account_no_verification' => 'Verification',
            'IP' => 'Ip',
            'created_datetime' => 'Created Datetime',
            'updated_datetime' => 'Updated Datetime',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }
    
    public function getBankName()
    {
        return $this->hasOne(\common\models\Banks::className(), ['id' => 'bank_name']);
    }
    
    public function getRealIp() {
        if (!empty($_SERVER['HTTP_CLIENT_IP'])) {   //check ip from share internet
            $ip = $_SERVER['HTTP_CLIENT_IP'];
        } elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {   //to check ip is pass from proxy
            $ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
        } else {
            $ip = $_SERVER['REMOTE_ADDR'];
        }
        return $ip;
    }
}

frontend/modules/painter/models/PainterProfile.php
<?php

namespace app\modules\painter\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;
use yii\db\Expression;
use yii\helpers\Url;
use yii\helpers\Html;
use borales\extensions\phoneInput\PhoneInputValidator;
//use borales\extensions\phoneInput\PhoneInputBehavior;

/**
 * This is the model class for table "painter_profile".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $card_id
 * @property string $photo
 * @property integer $title
 * @property string $full_name
 * @property string $profile_name
 * @property string $mobile
 * @property integer $nationality
 * @property string $ic_no
 * @property integer $race
 * @property integer $pic_name
 * @property string $created_datetime
 * @property string $updated_datetime
 * @property integer $created_by
 * @property integer $updated_by
 */
class PainterProfile extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    const STATUS_DELETED = 'X';
    const STATUS_ACTIVE = 'A';
    const STATUS_PENDING = 'P';
    public $status;
    public $snapdocument;
    public $files;
  
    
    public static function tableName()
    {
        return 'painter_profile';
    }
    
    public function behaviors() {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_datetime',
                'updatedAtAttribute' => 'updated_datetime',
                'value' => new Expression('NOW()'),                
            ],
            BlameableBehavior::className(),
            //'phoneInput' => PhoneInputBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'full_name', 'nationality', 'country', 'race','address','region_id','state_id','dob'], 'required'],
            [['user_id', 'title', 'country', 'race', 'created_by', 'updated_by'], 'integer'],
            [['card_num', 'card_id','pic_name'], 'string'],            
            ['ic_no', 'required'],
            ['ic_no', 'unique', 'message' => 'This {attribute} has already been taken.'],
            [['mobile'], 'string', 'max' => 20],
            ['mobile', 'required'],
            //[['mobile'], PhoneInputValidator::className(), 'region' => 'MY'],
            //[['email'], 'email'],
            //['email', 'required'],
            //['email', 'unique', 'message' => 'This {attribute} has already been taken.'],
            //[['pic_name'], 'string', 'max' => 40],
            [['dob','snapdocument','created_datetime', 'updated_datetime','pic_name'], 'safe'],
            [['photo'], 'string', 'max' => 200],            
            //[['files'], 'file', 'maxFiles' => 4],
            [['files'], 'file', 'maxFiles' => 5, 'skipOnEmpty' => true, 'extensions'=>['pdf','doc','docx','jpg','jpeg','png','bmp'], 'checkExtensionByMimeType'=>false],
            [['nationality','profile_status'], 'string', 'max' => 2],
            [['full_name', 'email'], 'string', 'max' => 255],            
            [['profile_name', 'ic_no'], 'string', 'max' => 20],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'card_id' => 'Membership No',
            'photo' => 'Photo',
            'title' => 'Title',
            'full_name' => 'Full Name',
            'profile_name' => 'Profile Name',
            'dob' => 'Date of Birth',
            'email' => 'Email',
            'mobile' => 'Mobile',
            'address' => 'Address',
            'region_id' => 'Region',
            'state_id' => 'State',
            'nationality' => 'Nationality',
            'country' => 'Country',
            'ic_no' => 'NRIC/Passport Number',
            'race' => 'Race',
            'profile_status' => 'Profile Status',
            'pic_name' => 'PIC Name',
            'created_datetime' => 'Created Datetime',
            'updated_datetime' => 'Updated Datetime',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }
    
    public function afterFind() {
        parent::afterFind();
        $this->full_name = strtoupper($this->full_name);
    }
    
    public function getUser() {
        return $this->hasOne(\common\models\User::className(), ['id' => 'user_id'])->
       andWhere(['status' =>! self::STATUS_DELETED]);
    }
    
    public function getProfileTitle()
    {
        return $this->hasOne(\common\models\TitleOptions::className(), ['id' => 'title']);
    }
    
    public function getProfileCountry()
    {
        return $this->hasOne(\common\models\Country::className(), ['id' => 'country']);
    }
    
    public function getProfileRace()
    {
        return $this->hasOne(\common\models\Race::className(), ['id' => 'race']);
    }
    
    public function getProfileRegion()
    {
        return $this->hasOne(\common\models\Region::className(), ['region_id' => 'region_id']);
    }
    
    public function getProfileState()
    {
        return $this->hasOne(\common\models\State::className(), ['state_id' => 'state_id']);
    }
        
    public function getStatusDescription() {
        $returnValue = "";
        if ($this->status == "X") {
            $returnValue = "Deleted";
        } else if ($this->status == "P") {
            $returnValue = "<span class='label label-warning'>Pending</span>";
        } else if ($this->status == "A") {
            $returnValue = "Active";
        }
        return $returnValue;
    }
    
    public function getStatusProfile() {
        $returnValue = "";
        if ($this->profile_status == "P") {
            $returnValue = "<span class='label label-warning'>Pending</span>";
        } else if ($this->profile_status == "R") {
            $returnValue = '<a href="javascript:;" onclick="viewremark('. $this->id .');return false;"><span class="label label-info">Review</span></a>';
        } else if ($this->profile_status == "D") {
            $returnValue = "<span class='label label-danger'>Decline</span>";
        } else if ($this->profile_status == "A") {
            $returnValue = "<span class='label label-success'>Approve</span>";
        } 
        return $returnValue;
    }
    
    public function getActions() {
        $returnValue = "";
        $returnValue = $returnValue . '<a href="' . Url::to(['/painter/painterprofile/view/','id' => $this->id]) . '" title="View Profile" ><i class="fa fa-fw fa-eye"></i></a>';
        //if ($this->profile_status == "P" || $this->profile_status == "R") {
            $returnValue = $returnValue . '<a href="' . Url::to(['/painter/painterprofile/viewapprove/','id' => $this->id]) . '" title="Activate Profile" ><i class="fa fa-fw fa-check"></i></a>';
        //}
        if($this->profile_status == "A"){
            $returnValue = $returnValue . '<a href="' . Url::to(['/painter/painterprofile/sendpassword/','id' => $this->id]) . '" title="Resend password" ><i class="fa fa-fw fa-envelope"></i></a>';
        }
        //['class' => 'btn btn-success', 'data-toggle' => 'modal', 'data-target' => '#myModal']
        //$returnValue = $returnValue . '<a href="' . Url::to(['/support/membershippack/update/','id' => $this->user_id]) . '" title="Activate Profile" onclick = "updateGuard('.$this->user_id.');return false;"><i class="fa fa-fw fa-briefcase"></i></a>';
        return $returnValue;
    }
}

frontend/modules/painter/views/painterprofile/_form_approve.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

use common\models\TitleOptions;
use common\models\Race;
use common\models\Banks;
use common\models\Country;
use common\models\DealerList;

/* @var $this yii\web\View */
/* @var $model app\modules\painter\models\PainterProfile */
/* @var $form yii\widgets\ActiveForm */

?>
<style>
.box .box-solid {
     background-color: #F8F8F8;
}
</style>


<div class="row">
<div class="col-xs-12 col-lg-12">
    <div class="painter-profile-form">

        <?php
        if($formapprove->isNewRecord){
            $action = 'approvel';
        }else {
            $action = 'approvel-update';
        }
                $form = ActiveForm::begin([
                    'method' => 'POST',
                    'action' => ['/painter/painterprofile/'.$action, 'id' => $model->id],
                ]);
                ?>

        <div class="box-success box view-item col-xs-12 col-lg-12">            

            <div class="row">
                <div class="col-xs-12 col-sm-4 col-lg-4">
                    <?php echo $form->field($model, 'profile_status')->dropDownList(["P" => "Pending", "A" => "Approve", "R" => "Review", "D" => "Decline"]); ?>
                </div>
            </div>
            
            <div class="row">
                <div class="col-xs-12 col-sm-4 col-lg-8"> 
                    <?= $form->field($formapprove, 'pa_remark')->textarea(['rows'=>5,'cols'=>5]); ?>
                    <?= $form->field($formapprove, 'pa_profileid')->hiddeninput(['value' => $model->id])->label(false); ?>
                </div>

            </div>
            <div class="form-group">
                <?= Html::submitButton($formapprove->isNewRecord ? 'Save' : 'Update', ['class' => $formapprove->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div> 
        </div>
        
      <?php ActiveForm::end(); ?>  
    </div>    
</div>
</div>

frontend/modules/painter/views/painterprofile/_form_bank.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

use common\models\TitleOptions;
use common\models\Race;
use common\models\Banks;
use common\models\Country;
use common\models\DealerList;

/* @var $this yii\web\View */
/* @var $model app\modules\painter\models\PainterProfile */
/* @var $form yii\widgets\ActiveForm */
$this->title = 'Update Painter Profile: ' . $model->full_name;
$this->params['breadcrumbs'][] = ['label' => 'Painter Profiles', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->full_name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<style>
.box .box-solid {
     background-color: #F8F8F8;
}
</style>

<div class="col-xs-12">
    <div class="col-lg-10 col-sm-10 col-xs-12 no-padding"><h3 class="box-title"><i class="fa fa-edit"></i> <?= Html::encode($this->title) ?></h3></div>
    <div class="col-lg-2 col-sm-2 col-xs-12 no-padding" style="padding-top: 20px !important;">
        <div class="col-xs-12 no-padding">
            <?php //if(Yii::$app->user->can("/painter/painterprofile/create")) { ?>
            <?= Html::a('Back', ['view', 'id' => $model->id], ['class' => 'btn btn-block btn btn-default']) ?>
	<?php //} ?>
        </div>
    </div>
</div>

<div class="col-xs-12 col-lg-12">
    <div class="painter-profile-form">
      <?php $form = ActiveForm::begin(); ?>

        <div class="box-success box view-item col-xs-12 col-lg-12">            

            <div class="box box-solid box-info col-xs-12 col-lg-12 no-padding">
                <div class="box-header with-border">
                    <h4 class="box-title"><i class="fa fa-info-circle"></i> <?php echo Yii::t('app', 'Banking Information'); ?></h4>
                </div>
                
                <div class="box-body">
                    <div class="col-xs-12 col-sm-12 col-lg-12 no-padding">
                        <div class="col-xs-12 col-sm-4 col-lg-4">
                            <?=
                            $form->field($bankingInformation, 'bank_name')->dropDownList(
                                    ArrayHelper::map(Banks::find()
                                            ->where(['status' => 'A'])
                                            ->all(), 'id', 'bank_name'), ['prompt' => '-- Select --']
                            )
                            ?>                
                        </div>
                        <div class="col-xs-12 col-sm-4 col-lg-4">
                            <?= $form->field($bankingInformation, 'account_name')->textInput(['maxlength' => true]) ?>               
                        </div>
                        <div class="col-xs-12 col-sm-4 col-lg-4">
                            <?= $form->field($bankingInformation, 'account_number')->textInput(['maxlength' => true]) ?>               
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-4 col-lg-3">
                            <?= $form->field($bankingInformation, 'account_ic_no')->textInput(['maxlength' => true]) ?>               
                        </div>
                    <div class="col-xs-12 col-sm-4 col-lg-3">
                            <label class="control-label" for="account_ic_no"></label>
                            <p><input type="checkbox"> Copy Profile NRIC <span id="painterprofile-ic_no"><?php echo $profile->ic_no ?></span></p>
                        </div>
                    
                    <div class="col-xs-12 col-sm-4 col-lg-3">
                        <?php
                        echo $form->field($bankingInformation, 'account_no_verification')->radioList(
			['Y' => 'Yes', 'N' => 'No']
   );
                        if($bankingInformation->account_no_verification == 'N'){
                            
                            $countredemption = \common\models\Redemption::find()->where(['painterID' => $bankingInformation->user_id])->count();
                            if($countredemption > 0){
                                $countredemption = \common\models\Redemption::find()->where(['painterID' => $bankingInformation->user_id])->one();
                                echo '<p class="text-danger" style="margin-top: 20px;">'.$countredemption->review_comment.'</p>';
                            }
                        }
                        ?>
                    </div>
                    
                </div>
            </div> 
            <div class="form-group">
                <?= Html::submitButton($bankingInformation->isNewRecord ? 'Create' : 'Update', ['class' => $bankingInformation->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div> 
        </div>
        
      <?php ActiveForm::end(); ?>  
    </div>    
</div>

<script language="JavaScript">    
    $('input[type="checkbox"]').click(function(){
            if($(this).prop("checked") == true){
                var acIC = $('#painterprofile-ic_no').text();
                $('#bankinginformation-account_ic_no').val(acIC);
                $('#bankinginformation-account_ic_no').prop('disabled',true);
            }
            else if($(this).prop("checked") == false){
                $('#bankinginformation-account_ic_no').val('');
                $('#bankinginformation-account_ic_no').prop('disabled',false);
            }
        });
</script>

frontend/modules/painter/views/painterprofile/_tab_bank.php
<?php
use yii\helpers\Html;
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<div class="row">
  <div class="col-xs-12">
	<h2 class="page-header">	
	<i class="fas fa-credit-card"></i> <?php echo Yii::t('app', 'Bank Information'); ?>
	<div class="pull-right">
	<?php //if((Yii::$app->user->can("/student/stu-master/update") && ($_REQUEST['id'] == Yii::$app->session->get('stu_id'))) || (in_array("SuperAdmin", $adminUser)) || Yii::$app->user->can("updateAllStuInfo")) { ?>
		<?= Html::a('<i class="fa fa-pencil-square-o"></i> '.Yii::t('app', 'Edit'), ['updatebank', 'id' => $model->id, 'tab' => 'bank'], ['class' => 'btn btn-primary btn-sm', 'id' => 'update-data']) ?>
	<?php //} ?>
	</div>
	</h2>
  </div><!-- /.col -->
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="col-md-3 col-sm-3 col-xs-6 edusec-profile-label"><?= $bankingInformation->getAttributeLabel('bank_name') ?></div>
        <div class="col-md-9 col-sm-9 col-xs-6 edusec-profile-text"><?= ($bankingInformation->bankName->bank_name) ? $bankingInformation->bankName->bank_name : Yii::$app->params['MsgNull'] ?></div>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="col-md-3 col-sm-3 col-xs-6 edusec-profile-label"><?= $bankingInformation->getAttributeLabel('account_name') ?></div>
        <div class="col-md-9 col-sm-9 col-xs-6 edusec-profile-text"><?= ($bankingInformation->account_name) ? $bankingInformation->account_name : Yii::$app->params['MsgNull'] ?></div>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="col-md-3 col-sm-3 col-xs-6 edusec-profile-label"><?= $bankingInformation->getAttributeLabel('account_number') ?></div>
        <div class="col-md-9 col-sm-9 col-xs-6 edusec-profile-text"><?= ($bankingInformation->account_number) ? $bankingInformation->account_number : Yii::$app->params['MsgNull'] ?></div>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="col-md-3 col-sm-3 col-xs-6 edusec-profile-label"><?= $bankingInformation->getAttributeLabel('account_ic_no') ?></div>
        <div class="col-md-9 col-sm-9 col-xs-6 edusec-profile-text"><?= ($bankingInformation->account_ic_no) ? $bankingInformation->account_ic_no : Yii::$app->params['MsgNull'] ?></div>
    </div> 
</div>

frontend/modules/painter/views/painterprofile/_tab_personal.php
<?php
use yii\helpers\Html;
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<div class="row">
  <div class="col-xs-12">
	<h2 class="page-header">	
	<i class="fa fa-street-view"></i> <?php echo Yii::t('app', 'Painter Profile Information'); ?>
	<div class="pull-right">
	<?php //if((Yii::$app->user->can("/student/stu-master/update") && ($_REQUEST['id'] == Yii::$app->session->get('stu_id'))) || (in_array("SuperAdmin", $adminUser)) || Yii::$app->user->can("updateAllStuInfo")) { ?>
		<?= Html::a('<i class="fa fa-pencil-square-o"></i> '.Yii::t('app', 'Edit'), ['updateprofile', 'id' => $model->id, 'tab' => 'personal'], ['class' => 'btn btn-primary btn-sm', 'id' => 'update-data']) ?>
	<?php //} ?>
	</div>
	</h2>
  </div><!-- /.col -->
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
    <table class="table table-striped">
        <tbody><tr>
                <th>Membership No</th>
                <td><?= $model->card_id ?></td>
            </tr>
            <tr>
                <th>Name</th>
                <td><?= Html::encode($model->full_name) ?></td>
            </tr>
            <tr>
                <th>PIC Name</th>
                <td><?= ($model->pic_name) ? $model->pic_name : Yii::$app->params['MsgNull'] ?></td>
            </tr>
            <tr>
                <th>Bank Name</th>
                <td><?= ($bankingInformation->bankName->bank_name) ? $bankingInformation->bankName->bank_name : Yii::$app->params['MsgNull'] ?></td>
            </tr>
            <tr>
                <th>Account Name</th>
                <td><?= ($bankingInformation->account_name) ? $bankingInformation->account_name : Yii::$app->params['MsgNull'] ?></td>
            </tr>
            <tr>
                <th>Account Number</th>
                <?php
                if ($bankingInformation->account_no_verification == 'Y') {
                    $verify = '<i class="fa fa-check text-green" aria-hidden="true"> Verified</i>';
                } else {
                    $verify = '<i class="fa fa-ban text-red" aria-hidden="true"> Not Verified</i>';
                }
                ?>
                <td><?= ($bankingInformation->account_number) ? $bankingInformation->account_number : Yii::$app->params['MsgNull'] ?> <?= $verify ?></td>
            </tr>
            <tr>
                <th>Email ID</th>
                <td><?= $user->email ?></td>
            </tr>
            <tr>
                <th>Mobile No</th>
                <td><?= $model->mobile ?></td>
            </tr>
            <tr>
                <th>Status</th>
                <td>
                    <?php
                    if ($model->profile_status == 'P') {
                        echo '<span class="label label-warning">Pending</span>';
                    } else if ($model->profile_status == 'R') {
                        echo '<span class="label label-info">Review</span>';
                    } else if ($model->profile_status == 'D') {
                        echo '<span class="label label-danger">Decline</span>';
                    } else if ($model->profile_status == 'A') {
                        echo '<span class="label label-success">Active</span>';
                    }
                    ?>
                </td>
            </tr>
        </tbody>
    </table>
</div>
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="col-md-3 col-sm-3 col-xs-6 edusec-profile-label"><?= $model->getAttributeLabel('full_name') ?></div>
        <div class="col-md-9 col-sm-9 col-xs-6 edusec-profile-text"><?= $model->profileTitle->title ?>. <?= ($model->full_name) ? $model->full_name : Yii::t("app", "Not Set") ?></div>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="col-md-3 col-sm-4 col-xs-6 edusec-profile-label"><?= $user->getAttributeLabel('email') ?></div>
        <div class="col-md-9 col-sm-8 col-xs-6 edusec-profile-text"><?=  $user->email ?></div>
    </div>
    <div class="col-md-12 col-xs-12 col-sm-12">
        <div class="col-lg-6 col-sm-6 col-xs-12 no-padding edusec-bg-row">
            <div class="col-lg-6 col-xs-6 edusec-profile-label"><?= $model->getAttributeLabel('dob') ?></div>
            <div class="col-lg-6 col-xs-6 edusec-profile-text"><?= date('jS F Y', strtotime($model->dob)) ?></div>
        </div>
        <div class="col-lg-6 col-sm-6 col-xs-12 no-padding">
            <div class="col-lg-6 col-xs-6 edusec-profile-label"><?= $model->getAttributeLabel('mobile') ?></div>
            <div class="col-lg-6 col-xs-6 edusec-profile-text"><?= $model->mobile ?></div>
        </div>
    </div>
    <div class="col-md-12 col-xs-12 col-sm-12">
        <div class="col-lg-6 col-sm-6 col-xs-12 no-padding edusec-bg-row">
            <div class="col-lg-6 col-xs-6 edusec-profile-label"><?= $model->getAttributeLabel('ic_no') ?></div>
            <div class="col-lg-6 col-xs-6 edusec-profile-text"><?= $model->ic_no ?></div>
        </div>
        <div class="col-lg-6 col-sm-6 col-xs-12 no-padding">
            <div class="col-lg-6 col-xs-6 edusec-profile-label"><?= $model->getAttributeLabel('race') ?></div>
            <div class="col-lg-6 col-xs-6 edusec-profile-text"><?= $model->profileRace->title ?></div>
        </div>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="col-md-3 col-sm-4 col-xs-6 edusec-profile-label"><?= $model->getAttributeLabel('address') ?></div>
        <div class="col-md-9 col-sm-8 col-xs-6 edusec-profile-text"><?= ($model->address) ? $model->address : Yii::t("app", "Not Set") ?></div>
    </div>
    <div class="col-md-12 col-xs-12 col-sm-12">
        <div class="col-lg-6 col-sm-6 col-xs-12 no-padding edusec-bg-row">
            <div class="col-lg-6 col-xs-6 edusec-profile-label"><?= $model->getAttributeLabel('nationality') ?></div>
            <div class="col-lg-6 col-xs-6 edusec-profile-text"><?= $model->nationality == 'L' ? 'Malaysian' : 'Non Malaysian' ?></div>
        </div>
        <div class="col-lg-6 col-sm-6 col-xs-12 no-padding">
            <div class="col-lg-6 col-xs-6 edusec-profile-label"><?= $model->getAttributeLabel('country') ?></div>
            <div class="col-lg-6 col-xs-6 edusec-profile-text"><?= $model->profileCountry->name ?></div>
        </div>
    </div>
    <div class="col-md-12 col-xs-12 col-sm-12">
        <div class="col-lg-6 col-sm-6 col-xs-12 no-padding edusec-bg-row">
            <div class="col-lg-6 col-xs-6 edusec-profile-label"><?= $model->getAttributeLabel('region_id') ?></div>
            <div class="col-lg-6 col-xs-6 edusec-profile-text"><?= $model->profileRegion->region_name ?></div>
        </div>
        <div class="col-lg-6 col-sm-6 col-xs-12 no-padding">
            <div class="col-lg-6 col-xs-6 edusec-profile-label"><?= $model->getAttributeLabel('state_id') ?></div>
            <div class="col-lg-6 col-xs-6 edusec-profile-text"><?= $model->profileState->state_name ?></div>
        </div>
    </div>
</div>

frontend/modules/painter/views/painterprofile/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\painter\models\PainterProfile */

$this->title = 'Register New Painter';
$this->params['breadcrumbs'][] = ['label' => 'Painter Profiles', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="col-xs-12">
  <div class="col-lg-4 col-sm-4 col-xs-12 no-padding"><h3 class="box-title"><i class="fa fa-plus"></i> <?= Html::encode($this->title) ?></h3></div>
</div>
<div class="painter-profile-create">
    <?= $this->render('_form', [
        'model' => $model,
        'companyInformation' => $companyInformation,
        'bankingInformation' => $bankingInformation,
        'useremail' => $useremail,
]) ?>

</div>